---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - certchecker.egarciam.com
  resources:
  - certificatechecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certchecker.egarciam.com
  resources:
  - certificatechecks/finalizers
  verbs:
  - update
- apiGroups:
  - certchecker.egarciam.com
  resources:
  - certificatechecks/status
  verbs:
  - get
  - patch
  - update
